In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [25]:
scaler = StandardScaler()

In [26]:
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [27]:
print(scaler.mean_)

[ 0.5  0.5]


In [28]:
print(scaler.transform(data))

[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [29]:
print(scaler.transform([[2, 2]]))

[[ 3.  3.]]


In [30]:
scaler.var_

array([ 0.25,  0.25])

## 改成物件導向

In [8]:
import numpy as np

In [13]:
class MynormalScaler:
    def __init__(self):
        self.data_mean_=None
        self.data_std_=None
        
    def fit(self ,data):
        self.data_mean_=np.mean(data,axis=0)
        self.data_std_=np.std(data,axis=0)
        
    def transform(self ,data):
        new_data=(np.array(data)-self.data_mean_)/(self.data_std_)
        return new_data
    
    def fit_transform(self ,data):
        self.fit(data)
        return self.transform(data)

In [14]:
myscaler=MynormalScaler()

In [15]:
data

[[0, 0], [0, 0], [1, 1], [1, 1]]

In [16]:
myscaler.fit(data)

In [17]:
myscaler.data_mean_

array([ 0.5,  0.5])

In [18]:
myscaler.data_std_

array([ 0.5,  0.5])

In [19]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [21]:
myscaler.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [22]:
myscaler.transform([[2, 2]])

array([[ 3.,  3.]])